/*
 * Copyright (c) 2017 Programming Systems Group, CS Department, FAU
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

package de.fau.cs.inf2.cas.ares.pcreation.rulesystem;

public enum FilterRuleType {
  ADD_DELETE_FOR_CHANGE_ROOT_STATEMENTS,
  ADD_INSERT_FOR_ALIGNMENTS,
  ADD_INSERT_FOR_CHANGE_ROOT_BODY_PAIRS,
  ADD_INSERT_FOR_STATEMENTS_BETWEEN_USES,
  AFFECT_NODES_OUTSIDE_METHOD_BLOCK,
  CASE_ANNOTATION_CHANGES,
  CHANGE_ROOT_MOVEMENTS,
  CHOICE_ANNOTATION_CHANGES,
  COMBINE_SUBCHANGES_OF_STATEMENTS,
  MATCH_ANNOTATION_CHANGES,
  REMOVE_ACCESS_CHANGES,
  REMOVE_BLOCK_CHANGES,
  REMOVE_CHANGES_IN_CHOICE,
  REMOVE_CHANGES_OF_NODES_WITH_IDENTICAL_TYPE,
  REMOVE_CHANGES_TO_WILDCARD_CHILDREN,
  REMOVE_CHANGES_WITH_IDENTICAL_PARTNERS,
  REMOVE_IDENTIFIER_CHANGES,
  REMOVE_IDENTIFIER_MOVES,
  REMOVE_INTEGER_LITERAL_CHANGES,
  REMOVE_MOVES_OBSOLETE_DUE_TO_WILDCARDS,
  REMOVE_STRUCTURE_NODE_CHANGES,
  REMOVE_SUB_CHANGES,
  REMOVE_WILDCARD_OR_USE_CHANGES,
  TRANSFORM_CLASS_CREATOR_DELETE,
  TRANSFORM_DECLARATION_CHANGES,
  TRANSFORM_DECLARATION_CHILDREN_CHANGES,
  TRANSFORM_FOR_MOVEMENT,
  TRANSFORM_IF_CHANGES,
  TRANSFORM_LIST_INITIALIZER_CHANGES,
  TRANSFORM_OR_CONDITION,
  TRANSFORM_STATEMENT_CHANGES,
  TRANSFORM_SWITCH_LABEL_CHANGES

}
